export type Category =
  | "brunch"
  | "dinner"
  | "coffee"
  | "nightlife"
  | "shop"
  | "visit"
  | "do"
  | "taste";

export const categories: { id: Category; label: string; color: string }[] = [
  { id: "brunch", label: "Brunch", color: "#E8927C" },
  { id: "dinner", label: "Dinner", color: "#C4555A" },
  { id: "coffee", label: "Coffee", color: "#A0522D" },
  { id: "nightlife", label: "Nightlife", color: "#8E44AD" },
  { id: "shop", label: "Shop", color: "#E84393" },
  { id: "visit", label: "Visit", color: "#2980B9" },
  { id: "do", label: "Do", color: "#27AE60" },
  { id: "taste", label: "Taste", color: "#E67E22" },
];

export interface Place {
  name: string;
  neighborhood: string;
  description: string;
  category: Category;
  subcategory?: string;
  lat: number;
  lng: number;
}

export interface Venue {
  name: string;
  neighborhood: string;
  description: string;
  type: "wedding" | "welcome";
  lat: number;
  lng: number;
}

export const venues: Venue[] = [
  {
    name: "Çırağan Palace",
    neighborhood: "Beşiktaş",
    description: "Wedding venue",
    type: "wedding",
    lat: 41.0465,
    lng: 29.024,
  },
  {
    name: "Mandarin Oriental – Olea Bosphorus Bar",
    neighborhood: "Kuruçeşme",
    description: "Welcome party",
    type: "welcome",
    lat: 41.0563,
    lng: 29.0346,
  },
];

export const places: Place[] = [
  // ── Brunch ──────────────────────────────────────────────
  {
    name: "Petra HQ",
    neighborhood: "Gayrettepe",
    description:
      "Extensive brunch menu, concept store inside, ideal for a hungover brunch :)",
    category: "brunch",
    lat: 41.0728,
    lng: 28.9878,
  },
  {
    name: "Petra Roasting Co",
    neighborhood: "Bebek",
    description:
      "Cafe with garden seating, might get pretty crowded on the weekends",
    category: "brunch",
    lat: 41.0773,
    lng: 29.0438,
  },
  {
    name: "Mangerie",
    neighborhood: "Bebek",
    description: "Great views, reservation recommended",
    category: "brunch",
    lat: 41.0779,
    lng: 29.0448,
  },
  {
    name: "Lucca",
    neighborhood: "Bebek",
    description: "Bistro/restaurant with outdoor seating",
    category: "brunch",
    lat: 41.0776,
    lng: 29.0428,
  },
  {
    name: "Bi Nevi Deli",
    neighborhood: "Etiler",
    description: "Vegan lunch spot",
    category: "brunch",
    lat: 41.0812,
    lng: 29.0278,
  },
  {
    name: "Delicatessen",
    neighborhood: "Etiler",
    description: "Trendy spot with cozy garden",
    category: "brunch",
    lat: 41.0818,
    lng: 29.0268,
  },
  {
    name: "Journey",
    neighborhood: "Cihangir",
    description: "Eclectic cafe, more traditionally Turkish",
    category: "brunch",
    lat: 41.0312,
    lng: 28.9828,
  },
  {
    name: "Pandeli",
    neighborhood: "Eminönü",
    description: "Historic restaurant located in the Spice Bazaar",
    category: "brunch",
    lat: 41.0168,
    lng: 28.9708,
  },
  {
    name: "Kıyı",
    neighborhood: "Tarabya",
    description:
      "Traditional Turkish seafood, best for late lunch on Sundays, reservation is a must",
    category: "brunch",
    lat: 41.1272,
    lng: 29.0532,
  },
  {
    name: "Batard",
    neighborhood: "Bomonti",
    description:
      "French inspired bistro, would also recommend for a nice hungover brunch",
    category: "brunch",
    lat: 41.0522,
    lng: 28.9788,
  },
  {
    name: "Kruvasan",
    neighborhood: "Nişantaşı",
    description: "Lol brunch spot with fresh croissants",
    category: "brunch",
    lat: 41.0478,
    lng: 28.9932,
  },
  {
    name: "Casa Cooklife",
    neighborhood: "Bomonti",
    description: "Asian inspired brunch spot",
    category: "brunch",
    lat: 41.0528,
    lng: 28.9778,
  },

  // ── Dinner: Turkish ─────────────────────────────────────
  {
    name: "Karaköy Lokantası",
    neighborhood: "Karaköy",
    description: "Classic Turkish mezzes, reservation recommended",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0222,
    lng: 28.9772,
  },
  {
    name: "Asmalı Cavit",
    neighborhood: "Beyoğlu",
    description: "Classic Turkish mezzes, very local and casual",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0335,
    lng: 28.9762,
  },
  {
    name: "Aheste",
    neighborhood: "Beyoğlu",
    description:
      "Turkish food with a modern twist, reservation recommended",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0328,
    lng: 28.9778,
  },
  {
    name: "Alaf",
    neighborhood: "Kuruçeşme",
    description:
      "Turkish food with a modern twist and outdoor seating, reservation recommended",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0622,
    lng: 29.0368,
  },
  {
    name: "Müver",
    neighborhood: "Karaköy",
    description:
      "Turkish food with a modern twist and great rooftop views, reservation recommended",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0218,
    lng: 28.9782,
  },
  {
    name: "Balıkçı Abdullah",
    neighborhood: "Beykoz",
    description: "Traditional Turkish seafood by the Bosphorus",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.1282,
    lng: 29.0908,
  },
  {
    name: "Biz Istanbul",
    neighborhood: "Taksim",
    description:
      "Traditional Turkish and Ottoman cuisine, also good spot for rooftop drinks, amazing views",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0372,
    lng: 28.9852,
  },
  {
    name: "Ahmet Ustam Ocakbaşı",
    neighborhood: "Maslak",
    description:
      "Traditional Turkish meat restaurant, think indoors barbecue with grilled meat",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.1072,
    lng: 29.0178,
  },
  {
    name: "Lokanta 1741",
    neighborhood: "Eminönü",
    description:
      "Turkish food with a modern twist and great cocktails, located inside a Turkish bath",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0162,
    lng: 28.9698,
  },
  {
    name: "Saloncuma",
    neighborhood: "Cihangir",
    description:
      "Turkish food with a modern twist inside an old apartment building, speakeasy vibes",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0318,
    lng: 28.9822,
  },
  {
    name: "İskele Restaurant",
    neighborhood: "Rumeli Hisarı",
    description: "Seafood place by the Bosphorus",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0838,
    lng: 29.0552,
  },
  {
    name: "Günaydın Kebap",
    neighborhood: "Etiler",
    description: "Classic Turkish kebap restaurant",
    category: "dinner",
    subcategory: "Turkish",
    lat: 41.0808,
    lng: 29.0282,
  },

  // ── Dinner: Fine Dining ─────────────────────────────────
  {
    name: "TURK Fatih Tutak",
    neighborhood: "Bomonti",
    description:
      "2 Michelin star restaurant with exceptional food, reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0518,
    lng: 28.9792,
  },
  {
    name: "Gallada",
    neighborhood: "Karaköy",
    description:
      "Turkish-Asian fusion by Fatih Tutak, reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0212,
    lng: 28.9768,
  },
  {
    name: "Neolokal",
    neighborhood: "Beyoğlu",
    description:
      "1 Michelin star restaurant with a plant based menu option, reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0338,
    lng: 28.9768,
  },
  {
    name: "Mikla",
    neighborhood: "Beyoğlu",
    description:
      "1 Michelin star rooftop restaurant with impeccable views of Istanbul, reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0342,
    lng: 28.9782,
  },
  {
    name: "Okra",
    neighborhood: "Taksim",
    description:
      "Mediterranean cuisine with stunning views of the city, reservation is recommended",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0378,
    lng: 28.9842,
  },
  {
    name: "Telezzüz",
    neighborhood: "Kuzguncuk",
    description:
      "Vegan fine dining restaurant, reservation is a must, keep in mind it's on the Asian side",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0322,
    lng: 29.0328,
  },
  {
    name: "Ulus 29",
    neighborhood: "Beşiktaş",
    description:
      "An Istanbul staple, with breath taking views of the Bosphorus, reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0528,
    lng: 29.0142,
  },
  {
    name: "Araka",
    neighborhood: "Yeniköy",
    description:
      "1 Michelin star restaurant with a mostly plant based menu, very small so reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.1122,
    lng: 29.0572,
  },
  {
    name: "Arkestra",
    neighborhood: "Etiler",
    description:
      "1 Michelin star restaurant with a vibey bar upstairs, reservation is a must",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0822,
    lng: 29.0262,
  },
  {
    name: "Yeni Lokanta",
    neighborhood: "Beyoğlu",
    description:
      "Turkish food with a modern twist, reservation is highly recommended",
    category: "dinner",
    subcategory: "Fine Dining",
    lat: 41.0348,
    lng: 28.9772,
  },

  // ── Dinner: International ───────────────────────────────
  {
    name: "1924 Istanbul",
    neighborhood: "Beyoğlu",
    description:
      "Historic Russian restaurant with amazing ambiance and drinks, reservation recommended",
    category: "dinner",
    subcategory: "International",
    lat: 41.0332,
    lng: 28.9758,
  },
  {
    name: "Beymen Brasserie",
    neighborhood: "Nişantaşı",
    description:
      "Classic bistro with outdoor seating, great for people watching",
    category: "dinner",
    subcategory: "International",
    lat: 41.0482,
    lng: 28.9938,
  },
  {
    name: "Nid Noi",
    neighborhood: "Nişantaşı",
    description:
      "Small local Thai restaurant with fresh and authentic ingredients",
    category: "dinner",
    subcategory: "International",
    lat: 41.0472,
    lng: 28.9922,
  },
  {
    name: "Foxy",
    neighborhood: "Nişantaşı",
    description:
      "Local wine bar with an extensive Turkish wine menu and tapas style food",
    category: "dinner",
    subcategory: "International",
    lat: 41.0488,
    lng: 28.9928,
  },
  {
    name: "Apartıman",
    neighborhood: "Yeniköy",
    description:
      "Bistro/wine bar with great food and outdoor seating, reservation recommended",
    category: "dinner",
    subcategory: "International",
    lat: 41.1128,
    lng: 29.0568,
  },
  {
    name: "Mezkla",
    neighborhood: "Etiler",
    description: "Mexican food with a hifi bar",
    category: "dinner",
    subcategory: "International",
    lat: 41.0815,
    lng: 29.0288,
  },
  {
    name: "Da Mario",
    neighborhood: "Etiler",
    description: "Classic Italian restaurant with outdoor seating",
    category: "dinner",
    subcategory: "International",
    lat: 41.0802,
    lng: 29.0272,
  },
  {
    name: "Inari Omakase",
    neighborhood: "Kuruçeşme",
    description: "Sushi place with great cocktails",
    category: "dinner",
    subcategory: "International",
    lat: 41.0628,
    lng: 29.0372,
  },
  {
    name: "Cozy",
    neighborhood: "Etiler",
    description:
      "Trendy restaurant that turns into a clubby scene which continues into the night",
    category: "dinner",
    subcategory: "International",
    lat: 41.082,
    lng: 29.0292,
  },
  {
    name: "Smelt & Co",
    neighborhood: "Balat",
    description: "Seafood and plant based cuisine",
    category: "dinner",
    subcategory: "International",
    lat: 41.0332,
    lng: 28.9488,
  },
  {
    name: "Gün Lokantası",
    neighborhood: "Beyoğlu",
    description:
      "Small place with innovative cuisine, reservation is a must",
    category: "dinner",
    subcategory: "International",
    lat: 41.0345,
    lng: 28.9775,
  },

  // ── Coffee & Snacks ─────────────────────────────────────
  {
    name: "Petra Roasting Co",
    neighborhood: "Multiple locations",
    description: "Specialty coffee roasters",
    category: "coffee",
    lat: 41.0775,
    lng: 29.044,
  },
  {
    name: "Kronotrop",
    neighborhood: "Multiple locations",
    description: "Specialty coffee",
    category: "coffee",
    lat: 41.034,
    lng: 28.9756,
  },
  {
    name: "POCO Coffee & Matcha Bar",
    neighborhood: "Multiple locations",
    description: "Coffee and matcha bar",
    category: "coffee",
    lat: 41.0484,
    lng: 28.9918,
  },
  {
    name: "Cup of Joy",
    neighborhood: "Multiple locations",
    description: "Cozy coffee shop",
    category: "coffee",
    lat: 41.0308,
    lng: 28.9832,
  },
  {
    name: "Harman Coffee",
    neighborhood: "Beyoğlu",
    description: "Local coffee spot",
    category: "coffee",
    lat: 41.0325,
    lng: 28.9758,
  },
  {
    name: "Norre",
    neighborhood: "Beyoğlu",
    description: "Coffee and snacks",
    category: "coffee",
    lat: 41.0322,
    lng: 28.9765,
  },
  {
    name: "Montag",
    neighborhood: "Bomonti",
    description: "Neighborhood coffee shop",
    category: "coffee",
    lat: 41.0532,
    lng: 28.9782,
  },
  {
    name: "Ninda",
    neighborhood: "Bebek",
    description: "Cafe in Bebek",
    category: "coffee",
    lat: 41.0768,
    lng: 29.0422,
  },

  // ── Nightlife ───────────────────────────────────────────
  {
    name: "Tavern",
    neighborhood: "Cihangir",
    description: "Bar in Cihangir",
    category: "nightlife",
    lat: 41.0302,
    lng: 28.9822,
  },
  {
    name: "Geyik",
    neighborhood: "Cihangir",
    description: "Bar in Cihangir",
    category: "nightlife",
    lat: 41.0306,
    lng: 28.9818,
  },
  {
    name: "Soho House Istanbul",
    neighborhood: "Beyoğlu",
    description: "Members club and hotel",
    category: "nightlife",
    lat: 41.033,
    lng: 28.9785,
  },
  {
    name: "Nardis Jazz Club",
    neighborhood: "Beyoğlu",
    description: "Live jazz venue",
    category: "nightlife",
    lat: 41.0258,
    lng: 28.9742,
  },
  {
    name: "Comedus",
    neighborhood: "Beyoğlu",
    description: "Bar in Beyoğlu",
    category: "nightlife",
    lat: 41.0334,
    lng: 28.977,
  },
  {
    name: "Momo",
    neighborhood: "Bebek",
    description: "Bar in Bebek",
    category: "nightlife",
    lat: 41.0766,
    lng: 29.0435,
  },
  {
    name: "Alexandra Cocktail Bar",
    neighborhood: "Arnavutköy",
    description: "Cocktail bar",
    category: "nightlife",
    lat: 41.0678,
    lng: 29.0362,
  },
  {
    name: "La Boom",
    neighborhood: "Emirgan",
    description: "Nightlife venue",
    category: "nightlife",
    lat: 41.0968,
    lng: 29.0478,
  },
  {
    name: "Bebek Hotel by the Stay",
    neighborhood: "Bebek",
    description: "Hotel bar in Bebek",
    category: "nightlife",
    lat: 41.0762,
    lng: 29.0428,
  },
  {
    name: "Kaia",
    neighborhood: "Bebek",
    description: "Bar in Bebek",
    category: "nightlife",
    lat: 41.078,
    lng: 29.0452,
  },

  // ── Shop: Accessories ───────────────────────────────────
  {
    name: "Misela",
    neighborhood: "Akaretler & Beyoğlu",
    description:
      "Luxury accessories brand with handbags, scarves and personalized made-to-order items",
    category: "shop",
    subcategory: "Accessories",
    lat: 41.0418,
    lng: 29.0022,
  },
  {
    name: "Mer's",
    neighborhood: "Multiple locations",
    description: "Trendy fine silver jewelry",
    category: "shop",
    subcategory: "Accessories",
    lat: 41.0474,
    lng: 28.9945,
  },
  {
    name: "Serena Uziyel",
    neighborhood: "İstinye",
    description: "Turkish shoe and bag designer",
    category: "shop",
    subcategory: "Accessories",
    lat: 41.1082,
    lng: 29.0562,
  },
  {
    name: "Mehry Mu",
    neighborhood: "Bebek",
    description: "Turkish bag designer",
    category: "shop",
    subcategory: "Accessories",
    lat: 41.0758,
    lng: 29.0418,
  },

  // ── Shop: Clothing ──────────────────────────────────────
  {
    name: "Fey",
    neighborhood: "Nişantaşı",
    description: "Clothing and concept store",
    category: "shop",
    subcategory: "Clothing",
    lat: 41.048,
    lng: 28.9925,
  },
  {
    name: "Vakko",
    neighborhood: "Multiple locations",
    description:
      "Department store with Turkish designers as well as global brands",
    category: "shop",
    subcategory: "Clothing",
    lat: 41.0476,
    lng: 28.9942,
  },
  {
    name: "Siedres",
    neighborhood: "Karaköy",
    description:
      "Turkish apparel and accessories store with a Mediterranean color palette",
    category: "shop",
    subcategory: "Clothing",
    lat: 41.0226,
    lng: 28.9778,
  },
  {
    name: "Faraway",
    neighborhood: "Multiple locations",
    description: "Turkish apparel store inspired by nature",
    category: "shop",
    subcategory: "Clothing",
    lat: 41.0468,
    lng: 28.9932,
  },
  {
    name: "Nackiye",
    neighborhood: "Beşiktaş",
    description:
      "Turkish apparel store with Eastern Mediterranean influence",
    category: "shop",
    subcategory: "Clothing",
    lat: 41.0428,
    lng: 29.0058,
  },

  // ── Shop: Lifestyle & Souvenirs ─────────────────────────
  {
    name: "Haremlique",
    neighborhood: "Multiple locations",
    description: "High quality Turkish home textile store",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0492,
    lng: 28.9948,
  },
  {
    name: "Homemade Aromaterapi",
    neighborhood: "Multiple locations",
    description: "Skincare and aromatherapy products",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0496,
    lng: 28.9955,
  },
  {
    name: "Iznik Works",
    neighborhood: "Grand Bazaar",
    description: "Traditional Turkish ceramic objects",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0108,
    lng: 28.9682,
  },
  {
    name: "Naya Studio",
    neighborhood: "Arnavutköy",
    description: "Home decor and artworks studio",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0682,
    lng: 29.0352,
  },
  {
    name: "Wohha",
    neighborhood: "Arnavutköy",
    description: "Local ceramics and home decor shop",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0685,
    lng: 29.0348,
  },
  {
    name: "Minoa",
    neighborhood: "Multiple locations",
    description: "Bookstore with cafe",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0336,
    lng: 28.9752,
  },
  {
    name: "Ali Muhiddin Hacı Bekir",
    neighborhood: "Eminönü",
    description: "Traditional Turkish delight shop",
    category: "shop",
    subcategory: "Lifestyle",
    lat: 41.0172,
    lng: 28.9702,
  },

  // ── Visit: History & Architecture ───────────────────────
  {
    name: "Blue Mosque",
    neighborhood: "Fatih",
    description: "Iconic Ottoman-era mosque",
    category: "visit",
    subcategory: "History",
    lat: 41.0054,
    lng: 28.9768,
  },
  {
    name: "Hagia Sophia",
    neighborhood: "Fatih",
    description: "Historic cathedral turned mosque",
    category: "visit",
    subcategory: "History",
    lat: 41.0086,
    lng: 28.9802,
  },
  {
    name: "Basilica Cistern",
    neighborhood: "Fatih",
    description: "Ancient underground water cistern",
    category: "visit",
    subcategory: "History",
    lat: 41.0084,
    lng: 28.9778,
  },
  {
    name: "Grand Bazaar",
    neighborhood: "Fatih",
    description: "One of the largest and oldest covered markets in the world",
    category: "visit",
    subcategory: "History",
    lat: 41.0107,
    lng: 28.968,
  },
  {
    name: "Süleymaniye Mosque",
    neighborhood: "Fatih",
    description: "Magnificent Ottoman mosque",
    category: "visit",
    subcategory: "History",
    lat: 41.0162,
    lng: 28.964,
  },
  {
    name: "The Spice Bazaar",
    neighborhood: "Eminönü",
    description: "Historic market filled with spices and Turkish delights",
    category: "visit",
    subcategory: "History",
    lat: 41.0167,
    lng: 28.9706,
  },
  {
    name: "Topkapı Palace",
    neighborhood: "Fatih",
    description: "Former residence of Ottoman sultans",
    category: "visit",
    subcategory: "History",
    lat: 41.0115,
    lng: 28.9833,
  },
  {
    name: "Galata Tower",
    neighborhood: "Beyoğlu",
    description: "Medieval stone tower with panoramic views",
    category: "visit",
    subcategory: "History",
    lat: 41.0256,
    lng: 28.9742,
  },

  // ── Visit: Arts & Culture ───────────────────────────────
  {
    name: "Istanbul Museum of Modern Art",
    neighborhood: "Karaköy",
    description: "Contemporary art museum",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0235,
    lng: 28.9835,
  },
  {
    name: "Istanbul Archaeological Museums",
    neighborhood: "Fatih",
    description: "Extensive archaeological collections",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0118,
    lng: 28.981,
  },
  {
    name: "Sakıp Sabancı Museum",
    neighborhood: "Emirgan",
    description: "Art museum on the Bosphorus",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.1028,
    lng: 29.0562,
  },
  {
    name: "Borusan Contemporary",
    neighborhood: "Rumeli Hisarı",
    description: "Contemporary art space",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0832,
    lng: 29.0558,
  },
  {
    name: "Zeyrek Çinili Hamam",
    neighborhood: "Fatih",
    description: "Historic tiled bathhouse turned cultural space",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0198,
    lng: 28.958,
  },
  {
    name: "Arter",
    neighborhood: "Beyoğlu",
    description: "Contemporary art museum",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0418,
    lng: 28.9828,
  },
  {
    name: "SALT",
    neighborhood: "Beyoğlu",
    description: "Cultural institution and research center",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0278,
    lng: 28.9745,
  },
  {
    name: "Dirimart",
    neighborhood: "Dolapdere",
    description: "Contemporary art gallery",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0425,
    lng: 28.9832,
  },
  {
    name: "Pilevneli",
    neighborhood: "Dolapdere",
    description: "Contemporary art gallery",
    category: "visit",
    subcategory: "Arts & Culture",
    lat: 41.0432,
    lng: 28.9822,
  },

  // ── Do: Explore & Shop ─────────────────────────────────
  {
    name: "Walk around Nişantaşı",
    neighborhood: "Şişli",
    description: "Stroll the charming shopping streets of Nişantaşı",
    category: "do",
    subcategory: "Explore",
    lat: 41.0485,
    lng: 28.9935,
  },
  {
    name: "Vintage shops in Cihangir & Galata",
    neighborhood: "Beyoğlu",
    description: "Browse vintage and secondhand shops",
    category: "do",
    subcategory: "Explore",
    lat: 41.0288,
    lng: 28.9758,
  },
  {
    name: "İstinyePark Mall",
    neighborhood: "İstinye",
    description: "Luxury stores in one of Istanbul's premier shopping malls",
    category: "do",
    subcategory: "Explore",
    lat: 41.1088,
    lng: 29.0558,
  },
  {
    name: "Zorlu Center",
    neighborhood: "Beşiktaş",
    description: "Luxury stores and entertainment complex",
    category: "do",
    subcategory: "Explore",
    lat: 41.0662,
    lng: 29.0168,
  },
  {
    name: "Ferry from Europe to Asia",
    neighborhood: "Kadıköy",
    description: "Ride the ferry across the Bosphorus to the Asian side",
    category: "do",
    subcategory: "Explore",
    lat: 41.0058,
    lng: 29.0228,
  },

  // ── Do: Nature & Wellness ──────────────────────────────
  {
    name: "Kılıç Ali Paşa Hamamı",
    neighborhood: "Karaköy",
    description: "Pamper yourself with a traditional Turkish bath experience",
    category: "do",
    subcategory: "Wellness",
    lat: 41.0258,
    lng: 28.9808,
  },
  {
    name: "Walk along the Bosphorus",
    neighborhood: "Bebek–Arnavutköy",
    description: "Scenic waterfront walk between Bebek and Arnavutköy",
    category: "do",
    subcategory: "Wellness",
    lat: 41.0722,
    lng: 29.0388,
  },
  {
    name: "Belgrad Forest",
    neighborhood: "Sarıyer",
    description: "Enjoy nature at Belgrad Forest's trails",
    category: "do",
    subcategory: "Wellness",
    lat: 41.1798,
    lng: 28.9798,
  },
  {
    name: "Dive into the Bosphorus",
    neighborhood: "Bebek",
    description: "Take a dip in the waters of the Bosphorus",
    category: "do",
    subcategory: "Wellness",
    lat: 41.0785,
    lng: 29.0452,
  },
  {
    name: "Row at the Golden Horn",
    neighborhood: "Eminönü",
    description: "Rowing on the historic Golden Horn waterway",
    category: "do",
    subcategory: "Wellness",
    lat: 41.0198,
    lng: 28.9548,
  },

  // ── Taste ───────────────────────────────────────────────
  {
    name: "Simit",
    neighborhood: "Street vendors citywide",
    description:
      "Turkish version of bagels with sesame, best enjoyed fresh from street vendors",
    category: "taste",
    lat: 41.0155,
    lng: 28.9718,
  },
  {
    name: "Döner",
    neighborhood: "Grand Bazaar area",
    description:
      "Turkish version of gyro/shawarma (but better), best in casual takeaway spots. Try Gül Ebru or Dönerci Şahin Usta near Grand Bazaar",
    category: "taste",
    lat: 41.0102,
    lng: 28.9692,
  },
  {
    name: "Rakı",
    neighborhood: "Available citywide",
    description:
      "Traditional Turkish liquor, goes best with seafood, grilled meat and mezzes",
    category: "taste",
    lat: 41.0208,
    lng: 28.9788,
  },
  {
    name: "Lokum (Turkish Delight)",
    neighborhood: "Eminönü",
    description:
      "Traditional confections with a variety of flavors. Ali Muhiddin Hacı Bekir in Eminönü is one of the best to take home as a souvenir",
    category: "taste",
    lat: 41.0178,
    lng: 28.9712,
  },
];
